### ISSUE TITLE
Maintenance status

### ISSUE THREAD

**Issue by Nuhvi** [raptorswing/rustydht-lib#73]
Hello, I am working on https://pkarr.org which is mostly a thin wrapper around BEP_0044 to enable DNS queries for Ed25519 keys.

I think this DHT implementation is the closest to something I can extend and add BEP_0044 support to. However, I am curious if you are still maintaining this library, so I can open a PR with minimal changes. Or should I just maintain a separate fork and be more liberal with the changes I would like to introduce, but also maintain it long-term?

Thanks and I appreciate your work on this.

**Comment by raptorswing** [comment]
Hi, thanks for reaching out.

> I am working on https://pkarr.org/ which is mostly a thin wrapper around BEP_0044 to enable DNS queries for Ed25519 keys.

Sounds like a cool project!

> I think this DHT implementation is the closest to something I can extend and add BEP_0044 support to. However, I am curious if you are still maintaining this library, so I can open a PR with minimal changes. Or should I just maintain a separate fork and be more liberal with the changes I would like to introduce, but also maintain it long-term?

As you can probably see from the commit history, I haven't been working on this recently. It's a hobby project that I did mainly for fun and to learn Rust. Where I'm at currently with life and this project, I'm happy to look at PRs/issues on a best-effort basis. Small, simple, and/or reasonable things have a pretty good chance of getting reviewed and merged. Large, complex, PRs, or ones requiring a lot of collaboration, on the other hand, may never get enough attention from me to reach the finish line.

So if your BEP0044 changes are small, I would tentatively say to do them here and I will try to help get them merged. But if you think it's going to be a lot of code, or pretty complex, or if there are other big features you're planning to implement, then you may be better served by forking the project.

> Thanks and I appreciate your work on this.

You're welcome! Looking through the code, there are definitely a few rough patches and things I would like to clean up, but I hope it can be useful to you.

**Comment by Nuhvi** [comment]
Thanks for the quick reply, I just wanted to confirm I am not fragmenting development. I will maintain a fork then. Thanks again.

**Comment by raptorswing** [comment]
Sounds good. Good luck!
